/*
 * generated by Xtext 2.25.0
 */
package it.unipr.ailab.jadescript.ide.contentassist.antlr;

import it.unipr.ailab.jadescript.ide.contentassist.antlr.internal.InternalJadescriptParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class JadescriptTokenSource extends AbstractIndentationTokenSource {

	public JadescriptTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalJadescriptParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalJadescriptParser.RULE_INDENT;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalJadescriptParser.RULE_DEDENT;
	}

	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
}
