/*
 * generated by Xtext 2.27.0
 */
package it.unipr.ailab.jadescript.ide.contentassist.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;

public class JadescriptTokenSource implements TokenSource {

	private final it.unipr.ailab.jadescript.parser.antlr.JadescriptTokenSource delegate;

	public JadescriptTokenSource(TokenSource delegate) {
		this.delegate = 
				new it.unipr.ailab.jadescript.parser.antlr.JadescriptTokenSource(delegate);
	}

	@Override
	public String getSourceName() {
		return delegate.getSourceName();
	}

	@Override
	public Token nextToken() {
		return delegate.nextToken();
	}
	
	

	
}
