/*
 * generated by Xtext 2.25.0
 */
package it.unipr.ailab.jadescript.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("restriction")
public class JadescriptDescriptionLabelProvider extends XbaseDescriptionLabelProvider {

	@Override
	public String image(IEObjectDescription ele) {
		return "logosmall.jpg";
	}
	
	// Labels and icons can be computed like this:
//	@Override
//	public String text(IEObjectDescription ele) {
//		return ele.getName().toString();
//	}
//	
//	@Override
//	public String image(IEObjectDescription ele) {
//		return ele.getEClass().getName() + ".gif";
//	}
}
