/*
 * generated by Xtext 2.12.0
 */
package it.unipr.ailab.jadescript.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class JadescriptProjectInfo extends DefaultProjectInfo {

}
