/*
 * generated by Xtext 2.12.0
 */
package it.unipr.ailab.jadescript.ui.wizard

import org.eclipse.xtext.generator.IFileSystemAccess2

class JadescriptNewProjectWizardInitialContents {
	

	def generateInitialContents(IFileSystemAccess2 fsa) {
		
	}
}
