/*
 * generated by Xtext 2.12.0
 */
package it.unipr.ailab.jadescript.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class JadescriptWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public JadescriptWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
