/*
 * generated by Xtext 2.25.0
 */
package it.unipr.ailab.jadescript;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JadescriptStandaloneSetup extends JadescriptStandaloneSetupGenerated {

	public static void doSetup() {
		new JadescriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
