/*
 * generated by Xtext 2.25.0
 */
package it.unipr.ailab.jadescript.tests

import org.eclipse.xtext.testing.InjectWith

@InjectWith(JadescriptInjectorProvider)
class JadescriptParsingTest {
	// Do not delete. The Xtext MWE2 generator would recreate this class with unneeded and missing dependencies.	
}
