/*
 * generated by Xtext 2.25.0
 */
package it.unipr.ailab.jadescript.ui;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.contentassist.CompletionPrefixProvider;
import org.eclipse.xtext.ui.editor.XtextEditor;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;
import org.eclipse.xtext.ui.editor.contentassist.ContentProposalLabelProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.hover.html.IEObjectHoverDocumentationProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

import com.google.inject.Binder;

import it.unipr.ailab.jadescript.ui.contentassist.IndentationAwareCompletionPrefixProviderWithFix;
import it.unipr.ailab.jadescript.ui.editor.JadescriptEditStrategyProvider;
import it.unipr.ailab.jadescript.ui.editor.JadescriptEditorExtended;
import it.unipr.ailab.jadescript.ui.hover.JadescriptEObjectHoverDocumentationProvider;
import it.unipr.ailab.jadescript.ui.hover.JadescriptEObjectHoverProvider;
import it.unipr.ailab.jadescript.ui.labeling.JadescriptLabelProvider;
import it.unipr.ailab.jadescript.ui.syntaxhighlight.JadescriptAntlrTokenToAttributeMapper;
import it.unipr.ailab.jadescript.ui.syntaxhighlight.JadescriptHighlightingConfiguration;
import it.unipr.ailab.jadescript.ui.syntaxhighlight.JadescriptSemanticHighlightingCalculator;
import it.unipr.ailab.jadescript.ui.wizard.JadescriptNewProjectWizard;
import it.unipr.ailab.jadescript.ui.wizard.JadescriptNewProjectWizardExtended;
import it.unipr.ailab.jadescript.ui.wizard.JadescriptProjectCreatorExtended;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JadescriptUiModule extends AbstractJadescriptUiModule {
	public JadescriptUiModule(final AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return JadescriptProjectCreatorExtended.class;
	}

	public Class<? extends JadescriptNewProjectWizard> bindNewProjectWizard() {
		return JadescriptNewProjectWizardExtended.class;
	}

	@Override
	public void configureContentProposalLabelProvider(final Binder binder) {
		binder.<ILabelProvider>bind(ILabelProvider.class)
				.annotatedWith(ContentProposalLabelProvider.class)
				.to(JadescriptLabelProvider.class);
	}
	
	@Override
	public Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider(){
		return JadescriptEditStrategyProvider.class;
	}
	
	@Override
	public Class<? extends org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator> bindIdeSemanticHighlightingCalculator() {
		return JadescriptSemanticHighlightingCalculator.class;
	}
	
	@Override
	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return JadescriptEObjectHoverProvider.class;
	}
	
	@Override
	public Class<? extends IEObjectHoverDocumentationProvider> bindIEObjectHoverDocumentationProvider() {
		return JadescriptEObjectHoverDocumentationProvider.class;
	}
	
	@Override
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return JadescriptHighlightingConfiguration.class;
	}
	
	@Override
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return JadescriptAntlrTokenToAttributeMapper.class;
	}
	
	@Override
	public Class<? extends XtextEditor> bindXtextEditor() {
		return JadescriptEditorExtended.class;
	}
	
	public Class<? extends CompletionPrefixProvider> bindCompletionPrefixProvider() {
		return IndentationAwareCompletionPrefixProviderWithFix.class;
	}
	
	
}
