package it.unipr.ailab.jadescript.semantics.context.location;

import it.unipr.ailab.jadescript.semantics.context.search.SearchLocation;

public class ContextGenerated extends SearchLocation {

    private static ContextGenerated instance = null;


    public static ContextGenerated getInstance() {
        if (instance == null) {
            instance = new ContextGenerated();
        }
        return instance;
    }


    @Override
    public boolean equals(Object obj) {
        return obj instanceof ContextGenerated;
    }


    @Override
    public int hashCode() {
        return System.identityHashCode(this);
    }


    @Override
    public String toString() {
        return "(generated by context)";
    }

}
