/*
 * generated by Xtext 2.25.0
 */
package it.unipr.ailab.jadescript.ide;


/**
 * Use this class to register ide components.
 */
public class JadescriptIdeModule extends AbstractJadescriptIdeModule {
}
