/*
 * generated by Xtext 2.27.0
 */
package it.unipr.ailab.jadescript.formatting2;

import it.unipr.ailab.jadescript.jadescript.Model;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.xbase.formatting2.XbaseFormatter;

@SuppressWarnings("restriction")
public class JadescriptFormatter extends XbaseFormatter {

    @SuppressWarnings("EmptyMethod")
    protected void format(Model model, IFormattableDocument doc) {
        // Default formatting disabled.
    }

}
