package jadescript.content.onto;

public interface Ontology_Vocabulary {
    String MAP_ENTRY = "JadescriptMapEntry";
    String SET_ENTRY = "JadescriptSetEntry";
    String LIST_ENTRY = "JadescriptListEntry";

    String KEYS = "keys";
    String VALUES = "values";

    String ELEMENTS = "elements";

    String PERFORMATIVE = "Performative";
    String PERFORMATIVE_CODE = "code";

    String DURATION = "Duration";
    String DURATION_SECONDSA = "secondsA";
    String DURATION_SECONDSB = "secondsB";
    String DURATION_MILLIS = "millis";

    String TIMESTAMP = "Timestamp";
    String TIMESTAMP_DATE = "date";
    String TIMESTAMP_ZONE_OFFSET = "zoneOffset";

    String PERCEPT = "Percept";
    String PERCEPT_CONTENT = "content";

    /* Base ontology content types */
    String DO_NOTHING = "DoNothing";
    String NOTHING = "Nothing";
    String FALSE_PREDICATE = "FalsePredicate";
    String TRUE_PREDICATE = "TruePredicate";
    String FALSE = "False";
    String TRUE = "True";

    String INTERNAL_EXCEPTION = "InternalException";

    String INTERNAL_EXCEPTION_DESCRIPTION = "description";

    String COULD_NOT_CONVERT = "CouldNotConvert";

    String COULD_NOT_CONVERT_VALUE = "value";
    String COULD_NOT_CONVERT_FROM_TYPE_NAME = "fromTypeName";

    String COULD_NOT_CONVERT_TO_TYPE_NAME = "toTypeName";


    // Generated by jadescript.content.onto.MessageContent#main(String[]), for Ontology_Vocabulary.java:
    String ACCEPTPROPOSALMESSAGE_CONTENT = "AcceptProposalMessageContent";
    String ACCEPTPROPOSALMESSAGE_ELEMENT0 = "element0";
    String ACCEPTPROPOSALMESSAGE_ELEMENT1 = "element1";

    String AGREEMESSAGE_CONTENT = "AgreeMessageContent";
    String AGREEMESSAGE_ELEMENT0 = "element0";
    String AGREEMESSAGE_ELEMENT1 = "element1";

    String CFPMESSAGE_CONTENT = "CFPMessageContent";
    String CFPMESSAGE_ELEMENT0 = "element0";
    String CFPMESSAGE_ELEMENT1 = "element1";

    String FAILUREMESSAGE_CONTENT = "FailureMessageContent";
    String FAILUREMESSAGE_ELEMENT0 = "element0";
    String FAILUREMESSAGE_ELEMENT1 = "element1";

    String NOTUNDERSTOODMESSAGE_CONTENT = "NotUnderstoodMessageContent";
    String NOTUNDERSTOODMESSAGE_ELEMENT0 = "element0";
    String NOTUNDERSTOODMESSAGE_ELEMENT1 = "element1";

    String PROPAGATEMESSAGE_CONTENT = "PropagateMessageContent";
    String PROPAGATEMESSAGE_ELEMENT0 = "element0";
    String PROPAGATEMESSAGE_ELEMENT1 = "element1";
    String PROPAGATEMESSAGE_ELEMENT2 = "element2";

    String PROPOSEMESSAGE_CONTENT = "ProposeMessageContent";
    String PROPOSEMESSAGE_ELEMENT0 = "element0";
    String PROPOSEMESSAGE_ELEMENT1 = "element1";

    String PROXYMESSAGE_CONTENT = "ProxyMessageContent";
    String PROXYMESSAGE_ELEMENT0 = "element0";
    String PROXYMESSAGE_ELEMENT1 = "element1";
    String PROXYMESSAGE_ELEMENT2 = "element2";

    String REFUSEMESSAGE_CONTENT = "RefuseMessageContent";
    String REFUSEMESSAGE_ELEMENT0 = "element0";
    String REFUSEMESSAGE_ELEMENT1 = "element1";

    String REJECTPROPOSALMESSAGE_CONTENT = "RejectProposalMessageContent";
    String REJECTPROPOSALMESSAGE_ELEMENT0 = "element0";
    String REJECTPROPOSALMESSAGE_ELEMENT1 = "element1";
    String REJECTPROPOSALMESSAGE_ELEMENT2 = "element2";

    String REQUESTWHENEVERMESSAGE_CONTENT = "RequestWheneverMessageContent";
    String REQUESTWHENEVERMESSAGE_ELEMENT0 = "element0";
    String REQUESTWHENEVERMESSAGE_ELEMENT1 = "element1";

    String REQUESTWHENMESSAGE_CONTENT = "RequestWhenMessageContent";
    String REQUESTWHENMESSAGE_ELEMENT0 = "element0";
    String REQUESTWHENMESSAGE_ELEMENT1 = "element1";

// End generated part.
}
